version: '3.9'
services:
  api:
    build:
      context: ./server-api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server-api:/app
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '5858:5858'
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: examplepass
      MONGO_HOST: mongo
      MONGO_PORT: 27017
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '5000:80'
    restart: always
    stdin_open: true
    tty: true
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepass
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
