version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '5000:80'
    restart: always
    stdin_open: true
    tty: true
  api:
    build:
      context: ./server-api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server-api:/app
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '5858:5858'
    env_file:
      - .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOST
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - WAIT_HOSTS=$WAIT_HOSTS
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
