version: '3.9'
services:
  api:
    build:
      context: ./server-api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server-api:/app
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '5858:5858'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '5000:80'
    restart: always
    stdin_open: true
    tty: true
