FROM node:alpine
RUN npm install -g npm
RUN npm install -g typescript

WORKDIR '/app'
COPY package.json .

RUN npm install npm-run-all
RUN npm install

COPY . .

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait


CMD /wait && npm run dev